-- MySQL Script generated by MySQL Workbench
-- Sun 06 Nov 2016 22:08:32 AEDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema geodb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `geodb` ;

-- -----------------------------------------------------
-- Schema geodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `geodb` DEFAULT CHARACTER SET utf8 ;
USE `geodb` ;

-- -----------------------------------------------------
-- Table `geodb`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geodb`.`game` ;

CREATE TABLE IF NOT EXISTS `geodb`.`game` (
  `pkey` INT NOT NULL AUTO_INCREMENT,
  `user` BIGINT NULL,
  `point` GEOMETRY NULL,
  `found` INT NULL DEFAULT 3,
  `gameNo` BIGINT NOT NULL,
  PRIMARY KEY (`pkey`),
  UNIQUE INDEX `gameNo_UNIQUE` (`gameNo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `geodb`.`ping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `geodb`.`ping` ;

CREATE TABLE IF NOT EXISTS `geodb`.`ping` (
  `pkey` INT NOT NULL AUTO_INCREMENT,
  `user` BIGINT NULL,
  `point` GEOMETRY NULL,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `game_gameNo` BIGINT NULL,
  `distToTarget` DOUBLE NULL,
  PRIMARY KEY (`pkey`, `time`),
  INDEX `fk_ping_game_idx` (`game_gameNo` ASC),
  CONSTRAINT `fk_ping_game`
    FOREIGN KEY (`game_gameNo`)
    REFERENCES `geodb`.`game` (`gameNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
